export const equipmentData = [
  {
    kategori: "Laptop",
    type: "Ultrabook",
    modell: "Dell XPS 13",
    bilde: "/xps.png",
  },
  {
    kategori: "Laptop",
    type: "Gaming",
    modell: "Asus ROG Zephyrus G14",
    bilde: "/zephyrus.png",
  },
  {
    kategori: "Skjerm",
    type: "4K",
    modell: "LG UltraFine 27UN850",
    bilde: "/ultrafine.png",
  },
  {
    kategori: "Skjerm",
    type: "Curved",
    modell: "Samsung Odyssey G7",
    bilde: "/odyssey.png",
  },
  {
    kategori: "Nettbrett",
    type: "Android",
    modell: "Samsung Galaxy Tab S8",
    bilde: "/galaxy.png",
  },
  {
    kategori: "Nettbrett",
    type: "iOS",
    modell: "iPad Pro 12.9",
    bilde: "/iPadPro.png",
  },
  {
    kategori: "Projektor",
    type: "Full HD",
    modell: "Epson EH-TW7100",
    bilde: "/epson.png",
  },
  {
    kategori: "Kamera",
    type: "Webkamera",
    modell: "Logitech C920 HD Pro",
    bilde: "/c920.png",
  },
  {
    kategori: "Headset",
    type: "Støyreduserende",
    modell: "Sony WH-1000XM5",
    bilde: "/sony.png",
  },
  {
    kategori: "Mobiltelefon",
    type: "Android",
    modell: "Google Pixel 8",
    bilde: "/pixel.png",
  },
];

export const ansatteData = [
  {
    id: 1,
    name: "Anna Johansen",
    position: "CEO",
    bio: "Anna har over 15 års erfaring i IT-bransjen og grunnla ImpactIT for å hjelpe bedrifter med å få tilgang til kvalitetsteknologi uten de høye forhåndskostnadene.",
    image: "/placeholder.svg?height=400&width=400",
    email: "anna@impact-it.no",
    phone: "+47 123 45 678",
    linkedin: "https://linkedin.com/",
  },
  {
    id: 2,
    name: "Erik Larsen",
    position: "CTO",
    bio: "Erik overvåker alle tekniske aspekter av utstyrsbeholdningen vår og sikrer at vi kun tilbyr den nyeste og mest pålitelige teknologien til våre kunder.",
    image: "/placeholder.svg?height=400&width=400",
    email: "erik@impact-it.no",
    phone: "+47 123 45 679",
    linkedin: "https://linkedin.com/",
  },
  {
    id: 3,
    name: "Sofia Berg",
    position: "Operations Manager",
    bio: "Sofia styrer vår daglige drift, og sikrer jevn utstyrslevering, vedlikehold og returer for alle våre kunder.",
    image: "/placeholder.svg?height=400&width=400",
    email: "sofia@impact-it.no",
    phone: "+47 123 45 680",
    linkedin: "https://linkedin.com/",
  },
  {
    id: 4,
    name: "Magnus Olsen",
    position: "Sales Director",
    bio: "Magnus leder salgsteamet vårt og jobber tett med kunder for å forstå deres teknologibehov og tilby skreddersydde utleieløsninger.",
    image: "/placeholder.svg?height=400&width=400",
    email: "magnus@impact-it.no",
    phone: "+47 123 45 681",
    linkedin: "https://linkedin.com/",
  },
  {
    id: 5,
    name: "Ingrid Hansen",
    position: "Customer Support Lead",
    bio: "Ingrid sikrer at våre kunder får eksepsjonell støtte gjennom hele leieperioden, fra teknisk assistanse til vedlikeholdsforespørsler.",
    image: "/placeholder.svg?height=400&width=400",
    email: "ingrid@impact-it.no",
    phone: "+47 123 45 682",
    linkedin: "https://linkedin.com/",
  },
  {
    id: 6,
    name: "Lars Nielsen",
    position: "Technical Specialist",
    bio: "Lars gir ekspert teknisk støtte og vedlikehold for alt utstyret vårt, og sikrer at alt fungerer perfekt for våre kunder.",
    image: "/placeholder.svg?height=400&width=400",
    email: "lars@impact-it.no",
    phone: "+47 123 45 683",
    linkedin: "https://linkedin.com/",
  },
];

export const utlånData = [
  {
    id: "RNT-1001",
    user: {
      name: "Morten Hansen",
      email: "morten.hansen@example.com",
      phone: "+47 123 45 678",
    },
    equipment: "Dell XPS 13",
    startDate: "2023-05-15",
    endDate: "2023-06-15",
    status: "Aktive",
    totalAmount: "kr 3,500",
  },
  {
    id: "RNT-1002",
    user: {
      name: "Sofie Berg",
      email: "sofie.berg@example.com",
      phone: "+47 234 56 789",
    },
    equipment: "LG UltraFine 27UN850",
    startDate: "2023-04-10",
    endDate: "2023-05-10",
    status: "Returnerte",
    totalAmount: "kr 2,200",
  },
  {
    id: "RNT-1003",
    user: {
      name: "Lars Nielsen",
      email: "lars.nielsen@example.com",
      phone: "+47 345 67 890",
    },
    equipment: "iPad Pro 12.9",
    startDate: "2023-05-01",
    endDate: "2023-06-01",
    status: "Aktive",
    totalAmount: "kr 2,800",
  },
  {
    id: "RNT-1004",
    user: {
      name: "Anna Johansen",
      email: "anna.johansen@example.com",
      phone: "+47 456 78 901",
    },
    equipment: "Sony WH-1000XM5",
    startDate: "2023-04-20",
    endDate: "2023-05-20",
    status: "Overdue",
    totalAmount: "kr 1,200",
  },
  {
    id: "RNT-1005",
    user: {
      name: "Erik Larsen",
      email: "erik.larsen@example.com",
      phone: "+47 567 89 012",
    },
    equipment: "Asus ROG Zephyrus G14",
    startDate: "2023-05-05",
    endDate: "2023-06-05",
    status: "Aktive",
    totalAmount: "kr 4,200",
  },
  {
    id: "RNT-1006",
    user: {
      name: "Ingrid Hansen",
      email: "ingrid.hansen@example.com",
      phone: "+47 678 90 123",
    },
    equipment: "Samsung Odyssey G7",
    startDate: "2023-03-15",
    endDate: "2023-04-15",
    status: "Returnerte",
    totalAmount: "kr 2,500",
  },
  {
    id: "RNT-1007",
    user: {
      name: "Magnus Olsen",
      email: "magnus.olsen@example.com",
      phone: "+47 789 01 234",
    },
    equipment: "Logitech C920 HD Pro",
    startDate: "2023-04-25",
    endDate: "2023-05-25",
    status: "Aktive",
    totalAmount: "kr 800",
  },
  {
    id: "RNT-1008",
    user: {
      name: "Sofia Berg",
      email: "sofia.berg@example.com",
      phone: "+47 890 12 345",
    },
    equipment: "Google Pixel 8",
    startDate: "2023-05-10",
    endDate: "2023-06-10",
    status: "Aktive",
    totalAmount: "kr 3,000",
  },
];
