export const equipmentData = [
    {
      kategori: "Laptop",
      type: "Ultrabook",
      modell: "Dell XPS 13",
      bilde: "/xps.png",
    },
    {
      kategori: "Laptop",
      type: "Gaming",
      modell: "Asus ROG Zephyrus G14",
      bilde: "/zephyrus.png",
    },
    {
      kategori: "Skjerm",
      type: "4K",
      modell: "LG UltraFine 27UN850",
      bilde: "/ultrafine.png",
    },
    {
      kategori: "Skjerm",
      type: "Curved",
      modell: "Samsung Odyssey G7",
      bilde: "/odyssey.png",
    },
    {
      kategori: "Nettbrett",
      type: "Android",
      modell: "Samsung Galaxy Tab S8",
      bilde: "/galaxy.png",
    },
    {
      kategori: "Nettbrett",
      type: "iOS",
      modell: "iPad Pro 12.9",
      bilde: "/iPadPro.png",
    },
    {
      kategori: "Projektor",
      type: "Full HD",
      modell: "Epson EH-TW7100",
      bilde: "/epson.png",
    },
    {
      kategori: "Kamera",
      type: "Webkamera",
      modell: "Logitech C920 HD Pro",
      bilde: "/c920.png",
    },
    {
      kategori: "Headset",
      type: "Støyreduserende",
      modell: "Sony WH-1000XM5",
      bilde: "/sony.png",
    },
    {
      kategori: "Mobiltelefon",
      type: "Android",
      modell: "Google Pixel 8",
      bilde: "/pixel.png",
    },
  ]
  
  export const ansatteData = [
    {
      id: 1,
      name: "Anna Johansen",
      position: "CEO",
      bio: "Anna har over 15 års erfaring i IT-bransjen og grunnla ImpactIT for å hjelpe bedrifter med å få tilgang til kvalitetsteknologi uten de høye forhåndskostnadene.",
      image: "/placeholder.svg?height=400&width=400",
      email: "anna@impact-it.no",
      phone: "+47 123 45 678",
      linkedin: "https://linkedin.com/",
    },
    {
      id: 2,
      name: "Erik Larsen",
      position: "CTO",
      bio: "Erik overvåker alle tekniske aspekter av utstyrsbeholdningen vår og sikrer at vi kun tilbyr den nyeste og mest pålitelige teknologien til våre kunder.",
      image: "/placeholder.svg?height=400&width=400",
      email: "erik@impact-it.no",
      phone: "+47 123 45 679",
      linkedin: "https://linkedin.com/",
    },
    {
      id: 3,
      name: "Sofia Berg",
      position: "Operations Manager",
      bio: "Sofia styrer vår daglige drift, og sikrer jevn utstyrslevering, vedlikehold og returer for alle våre kunder.",
      image: "/placeholder.svg?height=400&width=400",
      email: "sofia@impact-it.no",
      phone: "+47 123 45 680",
      linkedin: "https://linkedin.com/",
    },
    {
      id: 4,
      name: "Magnus Olsen",
      position: "Sales Director",
      bio: "Magnus leder salgsteamet vårt og jobber tett med kunder for å forstå deres teknologibehov og tilby skreddersydde utleieløsninger.",
      image: "/placeholder.svg?height=400&width=400",
      email: "magnus@impact-it.no",
      phone: "+47 123 45 681",
      linkedin: "https://linkedin.com/",
    },
    {
      id: 5,
      name: "Ingrid Hansen",
      position: "Customer Support Lead",
      bio: "Ingrid sikrer at våre kunder får eksepsjonell støtte gjennom hele leieperioden, fra teknisk assistanse til vedlikeholdsforespørsler.",
      image: "/placeholder.svg?height=400&width=400",
      email: "ingrid@impact-it.no",
      phone: "+47 123 45 682",
      linkedin: "https://linkedin.com/",
    },
    {
      id: 6,
      name: "Lars Nielsen",
      position: "Technical Specialist",
      bio: "Lars gir ekspert teknisk støtte og vedlikehold for alt utstyret vårt, og sikrer at alt fungerer perfekt for våre kunder.",
      image: "/placeholder.svg?height=400&width=400",
      email: "lars@impact-it.no",
      phone: "+47 123 45 683",
      linkedin: "https://linkedin.com/",
    },
  ]